[package]
name = "bitbuffer"
version = "1.2.0"
description = "A buffer for bit level and byte level manipulation"
repository = "https://github.com/NatLabs/BitBuffer"
keywords = [ "bits", "buffer", "byte", "blob", "data manipulation"]

[dependencies]
base = "0.8.1"
"buffer-deque" = "0.0.1"

[dev-dependencies]
test = "1.0.1"